{ 'log_level':'CRITICAL ', 'time_stamp':'12/22/2015 10:45:51 AM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'143', 'message':'HTTPConnectionPool(host='159.203.246.108', port=5000): Max retries exceeded with url: /sensors/sample_unit/sample_id/data/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f455c4a5fd0>: Failed to establish a new connection: [Errno 111] Connection refused',))' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/22/2015 10:46:00 AM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'143', 'message':'' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/22/2015 10:46:29 AM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'143', 'message':'' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/22/2015 10:47:59 AM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'143', 'message':'' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/22/2015 10:48:40 AM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'143', 'message':'' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/22/2015 10:49:14 AM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'143', 'message':'' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/22/2015 10:50:07 AM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'143', 'message':''dict' object has no attribute 'contains_key'' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/22/2015 10:51:10 AM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'143', 'message':'HTTPConnectionPool(host='159.203.246.108', port=5000): Max retries exceeded with url: /sensors/sample_unit/sample_id/data/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f53d0113fd0>: Failed to establish a new connection: [Errno 111] Connection refused',))' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/22/2015 10:51:33 AM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'143', 'message':'' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/22/2015 10:51:52 AM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'143', 'message':'' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/22/2015 10:52:06 AM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'143', 'message':''dict' object has no attribute 'contains_key'' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/22/2015 10:16:56 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'143', 'message':''dict' object has no attribute 'contains_key'' }
{ 'log_level':'ERROR    ', 'time_stamp':'12/23/2015 09:33:47 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'139', 'message':'command failed' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 09:33:47 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'142', 'message':'' }
{ 'log_level':'ERROR    ', 'time_stamp':'12/23/2015 09:35:56 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'145', 'message':'command failed' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 09:35:56 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'148', 'message':'' }
{ 'log_level':'ERROR    ', 'time_stamp':'12/23/2015 09:40:57 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'145', 'message':'command failed' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 09:40:57 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'148', 'message':'' }
{ 'log_level':'ERROR    ', 'time_stamp':'12/23/2015 09:41:41 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'145', 'message':'command failed' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 09:41:41 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'148', 'message':'' }
{ 'log_level':'ERROR    ', 'time_stamp':'12/23/2015 09:42:41 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'145', 'message':'command failed' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 09:42:41 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'148', 'message':'' }
{ 'log_level':'ERROR    ', 'time_stamp':'12/23/2015 09:46:04 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'146', 'message':'command failed' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 09:46:04 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'149', 'message':'' }
{ 'log_level':'ERROR    ', 'time_stamp':'12/23/2015 09:48:12 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'145', 'message':'command failed' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 09:48:12 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'148', 'message':'' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 09:55:04 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'148', 'message':'' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 09:55:56 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'148', 'message':'' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 09:56:02 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'148', 'message':'' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 09:59:16 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'148', 'message':'' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 10:00:50 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'148', 'message':'dictionary update sequence element #0 has length 1; 2 is required' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 10:01:56 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'149', 'message':'' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 10:03:08 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'150', 'message':'' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 10:04:05 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'150', 'message':'' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 10:08:27 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'151', 'message':'malformed string' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 10:09:51 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'152', 'message':'malformed string' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 10:10:44 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'152', 'message':'malformed string' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 10:12:16 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'152', 'message':'malformed string' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 10:13:19 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'152', 'message':'malformed string' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 10:14:20 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'152', 'message':'malformed string' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 10:14:44 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'152', 'message':'malformed string' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 10:15:03 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'152', 'message':'malformed string' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 10:19:28 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'153', 'message':'malformed string' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 10:19:55 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'153', 'message':'malformed string' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 10:20:19 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'153', 'message':'dictionary update sequence element #0 has length 1; 2 is required' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 10:20:52 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'153', 'message':'dictionary update sequence element #0 has length 1; 2 is required' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 10:21:09 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'153', 'message':'' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 10:21:50 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'153', 'message':'' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 10:22:16 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'153', 'message':'' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 10:26:29 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'159', 'message':''dict' object has no attribute 'contains_key'' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 10:27:23 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'159', 'message':'global name 'smart' is not defined' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 10:28:11 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'159', 'message':'' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 10:29:48 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'159', 'message':'local variable 'command' referenced before assignment' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 10:30:17 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'159', 'message':'global name 'smart' is not defined' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 10:33:06 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'152', 'message':'global name 'smart' is not defined' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 10:35:46 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'152', 'message':'global name 'smart' is not defined' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 10:36:50 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'152', 'message':'global name 'copy' is not defined' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 10:37:54 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'152', 'message':'' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 10:42:08 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'152', 'message':'' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 10:44:48 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'152', 'message':'' }
{ 'log_level':'CRITICAL ', 'time_stamp':'12/23/2015 10:45:27 PM CST', 'logger_name':'__main__    ', 'path_to_file':'smart.py', 'function_name':'process_arguments', 'line_number':'152', 'message':'' }
{ 'log_level':'ERROR    ', 'time_stamp':'12/23/2015 11:50:08 PM EST', 'logger_name':'__main__    ', 'path_to_file':'./smart/core/storage/access/restful_api_service.py', 'function_name':'insert_sensor_data_item', 'line_number':'48', 'message':'database names cannot contain the character ' '' }
{ 'log_level':'ERROR    ', 'time_stamp':'12/23/2015 11:51:13 PM EST', 'logger_name':'__main__    ', 'path_to_file':'./smart/core/storage/access/restful_api_service.py', 'function_name':'insert_sensor_data_item', 'line_number':'49', 'message':'database names cannot contain the character ' '' }
{ 'log_level':'ERROR    ', 'time_stamp':'12/23/2015 11:51:52 PM EST', 'logger_name':'__main__    ', 'path_to_file':'./smart/core/storage/access/restful_api_service.py', 'function_name':'insert_sensor_data_item', 'line_number':'47', 'message':'database names cannot contain the character ' '' }
{ 'log_level':'ERROR    ', 'time_stamp':'12/23/2015 11:53:50 PM EST', 'logger_name':'__main__    ', 'path_to_file':'./smart/core/storage/access/restful_api_service.py', 'function_name':'insert_sensor_data_item', 'line_number':'47', 'message':'database names cannot contain the character ' '' }
{ 'log_level':'ERROR    ', 'time_stamp':'12/23/2015 11:54:32 PM EST', 'logger_name':'__main__    ', 'path_to_file':'./smart/core/storage/access/restful_api_service.py', 'function_name':'insert_sensor_data_item', 'line_number':'47', 'message':'database names cannot contain the character ' '' }
{ 'log_level':'ERROR    ', 'time_stamp':'12/23/2015 11:55:23 PM EST', 'logger_name':'__main__    ', 'path_to_file':'./smart/core/storage/access/restful_api_service.py', 'function_name':'insert_sensor_data_item', 'line_number':'48', 'message':'database names cannot contain the character ' '' }
{ 'log_level':'ERROR    ', 'time_stamp':'12/23/2015 11:56:49 PM EST', 'logger_name':'__main__    ', 'path_to_file':'./smart/core/storage/access/restful_api_service.py', 'function_name':'insert_sensor_data_item', 'line_number':'49', 'message':'database names cannot contain the character ' '' }
{ 'log_level':'ERROR    ', 'time_stamp':'12/23/2015 11:57:30 PM EST', 'logger_name':'__main__    ', 'path_to_file':'./smart/core/storage/access/restful_api_service.py', 'function_name':'insert_sensor_data_item', 'line_number':'50', 'message':'database names cannot contain the character ' '' }
{ 'log_level':'ERROR    ', 'time_stamp':'12/23/2015 11:59:28 PM EST', 'logger_name':'__main__    ', 'path_to_file':'./smart/core/storage/access/restful_api_service.py', 'function_name':'insert_sensor_data_item', 'line_number':'49', 'message':'database names cannot contain the character ' '' }
{ 'log_level':'ERROR    ', 'time_stamp':'12/24/2015 12:01:06 AM EST', 'logger_name':'__main__    ', 'path_to_file':'./smart/core/storage/access/restful_api_service.py', 'function_name':'insert_sensor_data_item', 'line_number':'51', 'message':'database names cannot contain the character ' '' }
{ 'log_level':'WARNING  ', 'time_stamp':'12/24/2015 12:08:15 AM EST', 'logger_name':'__main__    ', 'path_to_file':'./smart/core/storage/access/restful_api_service.py', 'function_name':'read_sensor_data_item', 'line_number':'72', 'message':'No JSON object could be decoded' }
{ 'log_level':'WARNING  ', 'time_stamp':'12/24/2015 12:09:36 AM EST', 'logger_name':'__main__    ', 'path_to_file':'./smart/core/storage/access/restful_api_service.py', 'function_name':'read_sensor_data_item', 'line_number':'71', 'message':'No JSON object could be decoded' }
{ 'log_level':'WARNING  ', 'time_stamp':'12/24/2015 12:11:06 AM EST', 'logger_name':'__main__    ', 'path_to_file':'./smart/core/storage/access/restful_api_service.py', 'function_name':'read_sensor_data_item', 'line_number':'73', 'message':'No JSON object could be decoded' }
